import test from 'node:test';import assert from 'node:assert/strict';import handler,{validateInquiry,validateContent} from '../api/backend.js';
const good={source:'contact',consent:true,data:{'Your name':'Buyer','Work email':'buyer@example.com','Your message':'Need bags'}};
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test-key',ADMIN_EMAILS:'admin@example.com',SITE_ORIGIN:'https://manfanbag-website.vercel.app',RATE_LIMIT_SECRET:'test-secret'};Object.assign(process.env,env);
async function call(action,method='GET',body={},headers={}){let code,result;const req={query:{action},method,body,headers:{origin:env.SITE_ORIGIN,'content-type':'application/json',...headers},socket:{remoteAddress:'127.0.0.1'}};const response={headers:{},setHeader(k,v){this.headers[k]=v;},status(c){code=c;return this;},json(b){result=b;}};await handler(req,response);return {code,result,headers:response.headers};}
const response=x=>({ok:true,status:200,json:async()=>x});
test('inquiry requires valid email, required message, consent and known fields',()=>{assert.equal(validateInquiry(good)['Your name'],'Buyer');for(const b of [{...good,consent:false},{...good,data:{...good.data,'Work email':'invalid'}},{...good,data:{...good.data,'Your message':''}},{...good,data:{...good.data,status:'completed'}}])assert.throws(()=>validateInquiry(b));assert.throws(()=>validateInquiry({...good,source:'start-project'}));});
test('content rejects unsafe image URLs and malformed fields',()=>{const c={id:'bag',kind:'product',published:false,data:{title:'Bag',image:'javascript:alert(1)'}};assert.throws(()=>validateContent(c));assert.throws(()=>validateContent({...c,data:{title:'Bag',image:'//evil.com'}}));assert.equal(validateContent({...c,data:{title:'Bag',image:'https://example.com/a.png'}}).id,'bag');});
test('cross-site mutation rejected before data access',async()=>{const r=await call('content','POST',{}, {origin:'https://evil.example'});assert.equal(r.code,403);});
test('unauthenticated admin reads and writes denied',async()=>{for(const [action,method] of [['content','GET'],['inquiries','GET'],['content','POST'],['upload','POST'],['followup','POST']])assert.equal((await call(action,method)).code,401);});
test('public endpoint omits all draft body fields',async()=>{const old=global.fetch;global.fetch=async()=>response([{id:'secret',kind:'article',published:false,data:{title:'Private',body:'Secret'}},{id:'public',kind:'article',published:true,data:{title:'Public'}}]);try{const r=await call('public');assert.equal(r.code,200);assert.deepEqual(r.result[0],{id:'secret',kind:'article',published:false});assert.equal(r.result[1].data.title,'Public');}finally{global.fetch=old;}});
test('inquiry success only returned after confirmed database insert',async()=>{const old=global.fetch;let inserted=false;global.fetch=async(url,opts)=>{if(url.includes('/rpc/'))return response(true);inserted=true;assert.equal(JSON.parse(opts.body).data['Work email'],'buyer@example.com');return response([{id:'saved-id'}]);};try{const r=await call('inquiry','POST',good);assert.equal(r.code,201);assert.equal(r.result.id,'saved-id');assert.ok(inserted);}finally{global.fetch=old;}});
test('database failure never reports inquiry success',async()=>{const old=global.fetch;global.fetch=async url=>url.includes('/rpc/')?response(true):{ok:false};try{assert.equal((await call('inquiry','POST',good)).code,502);}finally{global.fetch=old;}});
test('rate limit blocks inquiry insert',async()=>{const old=global.fetch;global.fetch=async()=>response(false);try{assert.equal((await call('inquiry','POST',good)).code,429);}finally{global.fetch=old;}});
test('valid non-admin auth user denied',async()=>{const old=global.fetch;global.fetch=async()=>response({email:'other@example.com',email_confirmed_at:'now'});try{assert.equal((await call('inquiries','GET',{}, {cookie:'__Host-manfan_session=token'})).code,403);}finally{global.fetch=old;}});
test('admin login uses secure HttpOnly cookie, never returns tokens',async()=>{const old=global.fetch;global.fetch=async url=>response(url.includes('/rpc/')?true:{user:{email:'admin@example.com',email_confirmed_at:'now'},access_token:'secret-token',expires_in:3600});try{const r=await call('login','POST',{email:'admin@example.com',password:'test'});assert.equal(r.code,200);assert.match(r.headers['Set-Cookie'],/HttpOnly; SameSite=Strict/);assert.match(r.headers['Set-Cookie'],/Secure/);assert.equal(JSON.stringify(r.result).includes('secret-token'),false);}finally{global.fetch=old;}});
